spring:
  application:
    name: business-parking-response
  r2dbc:
    url: r2dbc:mariadb://localhost:${DB_PORT}/db_utp_parking?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT}/eureka/
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}